openapi: 3.1.0
info:
  title: Chroma Memory API
  version: "1.0"
servers:
  - url: https://chromamemory.onrender.com
paths:
  /store:
    post:
      operationId: store_memory
      summary: Store a memory entry with metadata including entity, platform, and thread context.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text content to store as memory
                metadata:
                  type: object
                  properties:
                    entity_id:
                      type: string
                      description: Unique ID of the user or entity
                    platform:
                      type: string
                      description: Platform of interaction (e.g., 'custom_gpt', 'whatsapp')
                    thread_id:
                      type: string
                      description: Thread or session identifier
                  required:
                    - entity_id
                    - platform
                    - thread_id
              required:
                - text
                - metadata
      responses:
        "200":
          description: Memory stored successfully

  /retrieve:
    post:
      operationId: retrieve_memory
      summary: Retrieve memory entries matching a semantic query and scoped by entity_id, platform, and thread_id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                entity_id:
                  type: string
                platform:
                  type: string
                thread_id:
                  type: string
                top_k:
                  type: integer
                  default: 5
              required:
                - query
                - entity_id
                - platform
                - thread_id
      responses:
        "200":
          description: Retrieval results
